from .base_model import BaseModel
from .perfil import Perfil
from .viagem import Viagem
from .endereco import Endereco
from .categoria import Categoria
from .atracao import Atracao
from .atividade import Atividade
from .local import Local
from .questao import Questao
from .resposta import Resposta
from .avaliacao import Avaliacao