# Generated by Django 5.0 on 2025-12-02 17:09

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nota', models.FloatField()),
                ('ingresso', models.BooleanField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('informacoes', models.TextField()),
                ('site', models.URLField()),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('classificacao', models.CharField(choices=[('Geral', 'General'), ('Famílias', 'Families'), ('Casais', 'Couples'), ('Solo', 'Solo'), ('Negócios', 'Business'), ('Adulto', 'Adult')], max_length=20)),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('logradouro', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('complemento', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('bairro', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cidade', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('estado', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('email', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('passaporte', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('data_nascimento', models.DateField()),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('genero', models.CharField(choices=[('Homen', 'Man'), ('Mulher', 'Woman'), ('Não Binario', 'Non Binary'), ('Não informado', 'Not Informed')], default='Não informado', max_length=20)),
                ('pagina_pessoal', models.URLField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(15)])),
                ('biografia', models.TextField(blank=True, null=True)),
                ('lingua', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('premium', models.BooleanField(default=False)),
                ('membro_desde', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('atracao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tripAdvisor.atracao')),
                ('turno', models.CharField(choices=[('Manhã', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=20)),
                ('duracao', models.TimeField()),
                ('guia', models.BooleanField()),
                ('participantes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dificuldade', models.CharField(choices=[('Fácil', 'Easy'), ('Média', 'Medium'), ('Difícil', 'Hard'), ('Muito Difícil', 'Ultra Hard')], max_length=20)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
            bases=('tripAdvisor.atracao',),
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('atracao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tripAdvisor.atracao')),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('acessibilidade', models.BooleanField()),
                ('classificacao', models.CharField(choices=[('Geral', 'General'), ('Famílias', 'Families'), ('Casais', 'Couples'), ('Solo', 'Solo'), ('Negócios', 'Business'), ('Adulto', 'Adult')], max_length=20)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
            bases=('tripAdvisor.atracao',),
        ),
        migrations.AddField(
            model_name='atracao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atracoes', to='tripAdvisor.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='atracao',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atracoes', to='tripAdvisor.endereco', verbose_name='Endereço Físico'),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('status', models.CharField(choices=[('Não Respondida', 'Not Answered'), ('Respondida', 'Answered'), ('Arquivada', 'Archived'), ('Fechada', 'Closed'), ('Moderada', 'Moderated'), ('Sinalizada', 'Flagged')], max_length=20)),
                ('data', models.DateField()),
                ('lides', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_publicadas', to='tripAdvisor.perfil', verbose_name='Autor da Questão')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('data', models.DateField()),
                ('lides', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_escritas', to='tripAdvisor.perfil', verbose_name='Autor da Resposta')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='tripAdvisor.questao', verbose_name='Questão Respondida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('pais_destino', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('inicio', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 12, 2), message='A data de início não pode ser no passado.')])),
                ('final', models.DateField()),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O orçamento deve ser zero ou um valor positivo.')])),
                ('proprosito', models.CharField(choices=[('Negócios', 'Business'), ('Férias', 'Vacation'), ('Mochilão', 'Backpacking'), ('Acadêmico', 'Academic'), ('Outro', 'Other')], max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('transporte', models.CharField(choices=[('Trem', 'Train'), ('Avião', 'Plane'), ('Carro', 'Car'), ('Ônibus', 'Bus'), ('Diversos', 'Several')], max_length=20)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='tripAdvisor.perfil', verbose_name='Dono da Viagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='atracao',
            name='viagens',
            field=models.ManyToManyField(related_name='atracoes_incluidas', to='tripAdvisor.viagem', verbose_name='Viagens Incluídas'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data_visita', models.DateField()),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('atracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='tripAdvisor.atracao', verbose_name='Atração Avaliada')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='tripAdvisor.perfil', verbose_name='Perfil Avaliador')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('perfil', 'atracao')},
            },
        ),
    ]
