# Generated by Django 5.0 on 2025-12-01 15:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('classificacao', models.CharField(choices=[('Geral', 'General'), ('Famílias', 'Families'), ('Casais', 'Couples'), ('Solo', 'Solo'), ('Negócios', 'Business'), ('Adulto', 'Adult')], max_length=20)),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('logradouro', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('complemento', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('bairro', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cidade', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('estado', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('passaporte', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('senha', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_nascimento', models.DateField()),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('genero', models.CharField(choices=[('Homen', 'Man'), ('Mulher', 'Woman'), ('Não Binario', 'Non Binary'), ('Não informado', 'Not Informed')], default='Não informado', max_length=20)),
                ('pagina_pessoal', models.URLField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(15)])),
                ('biografia', models.TextField(blank=True, null=True)),
                ('lingua', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('premium', models.BooleanField(default=False)),
                ('membro_desde', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('pais_destino', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('inicio', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 12, 1), message='A data de início não pode ser no passado.')])),
                ('final', models.DateField()),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O orçamento deve ser zero ou um valor positivo.')])),
                ('proprosito', models.CharField(choices=[('Negócios', 'Business'), ('Férias', 'Vacation'), ('Mochilão', 'Backpacking'), ('Acadêmico', 'Academic'), ('Outro', 'Other')], max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('transporte', models.CharField(choices=[('Trem', 'Train'), ('Avião', 'Plane'), ('Carro', 'Car'), ('Ônibus', 'Bus'), ('Diversos', 'Several')], max_length=20)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='tripAdvisor.perfil', verbose_name='Dono da Viagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
