# Generated by Django 5.0 on 2025-12-01 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAdvisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nota', models.FloatField()),
                ('ingresso', models.BooleanField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('informacoes', models.TextField()),
                ('site', models.URLField()),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('atracao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tripAdvisor.atracao')),
                ('turno', models.CharField(choices=[('Manhã', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=20)),
                ('duracao', models.TimeField()),
                ('guia', models.BooleanField()),
                ('participantes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dificuldade', models.CharField(choices=[('Fácil', 'Easy'), ('Média', 'Medium'), ('Difícil', 'Hard'), ('Muito Difícil', 'Ultra Hard')], max_length=20)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
            bases=('tripAdvisor.atracao',),
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('atracao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tripAdvisor.atracao')),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('acessibilidade', models.BooleanField()),
                ('classificacao', models.CharField(choices=[('Geral', 'General'), ('Famílias', 'Families'), ('Casais', 'Couples'), ('Solo', 'Solo'), ('Negócios', 'Business'), ('Adulto', 'Adult')], max_length=20)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
            bases=('tripAdvisor.atracao',),
        ),
    ]
