# Generated by Django 5.0 on 2025-12-03 23:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAdvisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='viagens',
            field=models.ManyToManyField(blank=True, null=True, related_name='atracoes_incluidas', to='tripAdvisor.viagem', verbose_name='Viagens Incluídas'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 12, 3), message='A data de início não pode ser no passado.')]),
        ),
    ]
