# Generated by Django 5.0 on 2025-12-01 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAdvisor', '0002_atracao_atividade_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('status', models.CharField(choices=[('Não Respondida', 'Not Answered'), ('Respondida', 'Answered'), ('Arquivada', 'Archived'), ('Fechada', 'Closed'), ('Moderada', 'Moderated'), ('Sinalizada', 'Flagged')], max_length=20)),
                ('data', models.DateField()),
                ('lides', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_publicadas', to='tripAdvisor.perfil', verbose_name='Autor da Questão')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('data', models.DateField()),
                ('lides', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_escritas', to='tripAdvisor.perfil', verbose_name='Autor da Resposta')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='tripAdvisor.questao', verbose_name='Questão Respondida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
