# Generated by Django 5.0 on 2025-12-06 11:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAdvisor', '0002_alter_atracao_viagens_alter_viagem_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='viagens',
        ),
        migrations.AddField(
            model_name='viagem',
            name='atracoes',
            field=models.ManyToManyField(blank=True, related_name='viagens', to='tripAdvisor.atracao', verbose_name='Atrações da Viagem'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 12, 6), message='A data de início não pode ser no passado.')]),
        ),
    ]
