# Generated by Django 5.0 on 2025-12-01 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAdvisor', '0003_questao_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atracoes', to='tripAdvisor.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='atracao',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atracoes', to='tripAdvisor.endereco', verbose_name='Endereço Físico'),
        ),
        migrations.AddField(
            model_name='atracao',
            name='viagens',
            field=models.ManyToManyField(related_name='atracoes_incluidas', to='tripAdvisor.viagem', verbose_name='Viagens Incluídas'),
        ),
    ]
