# Generated by Django 5.0 on 2025-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAdvisor', '0003_remove_atracao_viagens_viagem_atracoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='atracoes',
            field=models.ManyToManyField(blank=True, null=True, related_name='viagens', to='tripAdvisor.atracao', verbose_name='Atrações da Viagem'),
        ),
    ]
