# Generated by Django 5.0 on 2025-12-01 18:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripAdvisor', '0004_atracao_categoria_atracao_endereco_atracao_viagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data_visita', models.DateField()),
                ('data_avaliacao', models.DateField(default=datetime.date(2025, 12, 1))),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('atracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='tripAdvisor.atracao', verbose_name='Atração Avaliada')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='tripAdvisor.perfil', verbose_name='Perfil Avaliador')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('perfil', 'atracao')},
            },
        ),
    ]
