# Generated by Django 5.0 on 2025-12-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripAdvisor', '0004_alter_viagem_atracoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viagem',
            old_name='proprosito',
            new_name='proposito',
        ),
    ]
